"""Transparent load monitor for the shared Home Assistant Modbus hub.

The monitor does not issue its own Modbus requests. It wraps the existing
hub.async_pb_call() and hub.low_level_pb_call() methods and measures traffic
generated by all users of this hub: normal HA polling, scripts and bolid_events.

Home Assistant Modbus serializes async_pb_call() with one asyncio.Lock. Because
low_level_pb_call() is invoked only after that lock is acquired, the interval
between entering async_pb_call() and entering low_level_pb_call() is a useful
measurement of queue wait. The interval spent in low_level_pb_call() is the
actual pymodbus request/response transaction. The remaining time before
async_pb_call() returns is primarily message_wait_milliseconds plus small
framework overhead.
"""

from __future__ import annotations

import asyncio
from collections import Counter, deque
from contextvars import ContextVar
from dataclasses import dataclass
import logging
from math import ceil
from time import monotonic
from typing import Any, Awaitable, Callable

from homeassistant.components.modbus.const import (
    CALL_TYPE_COIL,
    CALL_TYPE_REGISTER_HOLDING,
    CALL_TYPE_WRITE_COIL,
    CALL_TYPE_WRITE_COILS,
    CALL_TYPE_WRITE_REGISTER,
    CALL_TYPE_WRITE_REGISTERS,
)

_LOGGER = logging.getLogger(__name__)

SLOW_TRANSACTION_MS = 500.0

DiagnosticCallback = Callable[..., Awaitable[None]]


@dataclass(slots=True)
class _CallContext:
    """Timing context for one async_pb_call()."""

    started: float
    low_started: float | None = None
    low_finished: float | None = None
    low_response_type: str | None = None
    low_is_error: bool | None = None
    exception_code: int | None = None

    # Raw pymodbus result captured before Home Assistant low_level_pb_call()
    # converts ExceptionResponse/isError into None.
    raw_response_type: str | None = None
    raw_is_error: bool | None = None
    raw_exception_code: int | None = None
    raw_function_code: int | None = None
    raw_retries: int | None = None
    raw_transaction_id: int | None = None
    raw_exception_type: str | None = None
    raw_exception_text: str | None = None


@dataclass(slots=True)
class _Sample:
    """One completed Modbus hub call."""

    finished: float
    address: int
    call_type: str
    category: str
    success: bool
    total_ms: float
    queue_wait_ms: float | None
    transaction_ms: float | None
    post_transaction_ms: float | None
    lock_hold_ms: float | None
    response_type: str | None
    exception_code: int | None
    request_value: Any
    raw_response_type: str | None
    raw_is_error: bool | None
    raw_exception_code: int | None
    raw_function_code: int | None
    raw_retries: int | None
    raw_transaction_id: int | None
    raw_exception_type: str | None
    raw_exception_text: str | None


def _percentile(values: list[float], percentile: float) -> float | None:
    """Nearest-rank percentile."""
    if not values:
        return None
    ordered = sorted(values)
    rank = max(1, ceil(percentile * len(ordered)))
    return ordered[min(rank - 1, len(ordered) - 1)]


def _stats(values: list[float]) -> dict[str, float | None]:
    """Compact latency statistics."""
    if not values:
        return {
            "avg": None,
            "p50": None,
            "p95": None,
            "max": None,
        }
    return {
        "avg": round(sum(values) / len(values), 2),
        "p50": round(_percentile(values, 0.50), 2),
        "p95": round(_percentile(values, 0.95), 2),
        "max": round(max(values), 2),
    }


def _classify(address: int, call_type: str) -> str:
    """Classify a request by its role in the current Bolid integration."""
    if address == 46264 and call_type == CALL_TYPE_REGISTER_HOLDING:
        return "event_read"
    if address == 46163 and call_type == CALL_TYPE_WRITE_REGISTER:
        return "event_ack"

    # Служебный numeric interface type 6.
    if address in (46179, 46328):
        return "numeric_service"

    # Служебные регистры event buffer/status.
    if 46160 <= address <= 46350:
        return "pp_service"

    # Старый интерфейс зон: чтение/управление через 40000+.
    if 40000 <= address < 46000:
        if call_type == CALL_TYPE_REGISTER_HOLDING:
            return "zone_read"
        if call_type in (CALL_TYPE_WRITE_REGISTER, CALL_TYPE_WRITE_REGISTERS):
            return "zone_write"
        return "zone_other"

    # Реле ПП: coils 10000+.
    if 10000 <= address < 20000:
        if call_type == CALL_TYPE_COIL:
            return "relay_read"
        if call_type in (CALL_TYPE_WRITE_COIL, CALL_TYPE_WRITE_COILS):
            return "relay_write"
        return "relay_other"

    return "other"


class ModbusHubLoadMonitor:
    """Measure actual traffic and queueing on one Home Assistant Modbus hub."""

    def __init__(
        self,
        hub: Any,
        diagnostic_callback: DiagnosticCallback,
        report_interval: float,
        summary_interval: float,
    ) -> None:
        self.hub = hub
        self._diag = diagnostic_callback
        self.report_interval = report_interval
        self.summary_interval = summary_interval

        self._samples: deque[_Sample] = deque()
        self._context: ContextVar[_CallContext | None] = ContextVar(
            "bolid_modbus_load_context",
            default=None,
        )

        self._task: asyncio.Task | None = None
        self._stopping = False
        self._installed = False
        self._started_at = monotonic()
        self._last_report_at = self._started_at
        self._last_summary_at = self._started_at

        self._active_calls = 0
        self._window_max_in_flight = 0
        self._summary_max_in_flight = 0

        self._original_async_pb_call: Any = None
        self._original_low_level_pb_call: Any = None
        self._previous_async_instance_attr: Any = None
        self._previous_low_instance_attr: Any = None
        self._had_async_instance_attr = False
        self._had_low_instance_attr = False
        self._wrapped_async_pb_call: Any = None
        self._wrapped_low_level_pb_call: Any = None

        # Deep tap: original HA _pb_request entries point directly to pymodbus
        # client methods. Wrapping those methods lets us see ExceptionResponse
        # before Home Assistant converts it to None.
        self._original_pb_entries: dict[str, Any] = {}
        self._wrapped_pb_funcs: dict[str, Any] = {}

        # Capture the exact HA Modbus error text into our JSONL as well.
        self._original_log_error: Any = None
        self._wrapped_log_error: Any = None
        self._had_log_error_instance_attr = False
        self._previous_log_error_instance_attr: Any = None

    @property
    def configured_message_wait_ms(self) -> float | None:
        """Configured message_wait_milliseconds from the HA Modbus hub."""
        value = getattr(self.hub, "_msg_wait", None)
        if value is None:
            return None
        return round(float(value) * 1000.0, 2)

    @staticmethod
    def _safe_int(value: Any) -> int | None:
        """Convert a diagnostic field to int without affecting communication."""
        if value is None:
            return None
        try:
            return int(value)
        except (TypeError, ValueError):
            return None

    def _sample_details(self, sample: _Sample) -> dict[str, Any]:
        """Fields useful for one abnormal Modbus call."""
        return {
            "category": sample.category,
            "call_type": sample.call_type,
            "address": sample.address,
            "request_value": sample.request_value,
            "success": sample.success,
            "total_ms": round(sample.total_ms, 2),
            "queue_wait_ms": (
                round(sample.queue_wait_ms, 2)
                if sample.queue_wait_ms is not None
                else None
            ),
            "transaction_ms": (
                round(sample.transaction_ms, 2)
                if sample.transaction_ms is not None
                else None
            ),
            "post_transaction_ms": (
                round(sample.post_transaction_ms, 2)
                if sample.post_transaction_ms is not None
                else None
            ),
            "response_type": sample.response_type,
            "exception_code": sample.exception_code,
            "raw_response_type": sample.raw_response_type,
            "raw_is_error": sample.raw_is_error,
            "raw_exception_code": sample.raw_exception_code,
            "raw_function_code": sample.raw_function_code,
            "raw_retries": sample.raw_retries,
            "raw_transaction_id": sample.raw_transaction_id,
            "raw_exception_type": sample.raw_exception_type,
            "raw_exception_text": sample.raw_exception_text,
        }

    def _schedule_diag(self, level: str, message: str, **data: Any) -> None:
        """Write a diagnostic asynchronously without delaying the Modbus caller."""
        try:
            asyncio.create_task(
                self._diag(level, message, **data),
                name=f"bolid-{message}",
            )
        except RuntimeError:
            # Event loop is already stopping.
            pass

    async def start(self) -> None:
        """Install transparent wrappers and start periodic reporting."""
        if self._installed:
            return

        # Preserve whether somebody had already overridden methods on this instance.
        hub_dict = getattr(self.hub, "__dict__", {})
        self._had_async_instance_attr = "async_pb_call" in hub_dict
        self._had_low_instance_attr = "low_level_pb_call" in hub_dict
        self._previous_async_instance_attr = hub_dict.get("async_pb_call")
        self._previous_low_instance_attr = hub_dict.get("low_level_pb_call")

        self._original_async_pb_call = self.hub.async_pb_call
        self._original_low_level_pb_call = self.hub.low_level_pb_call

        # ----------------------------------------------------------
        # Raw pymodbus tap.
        # ----------------------------------------------------------
        # HA stores the actual client methods in hub._pb_request. The wrapper
        # only observes their result and then returns exactly the same object.
        pb_request = getattr(self.hub, "_pb_request", {})
        for call_type, entry in list(pb_request.items()):
            original_func = entry.func
            self._original_pb_entries[call_type] = entry

            async def wrapped_pb_func(
                address: int,
                *args: Any,
                _original_func: Any = original_func,
                **kwargs: Any,
            ) -> Any:
                ctx = self._context.get()
                try:
                    raw_result = await _original_func(address, *args, **kwargs)
                except Exception as err:
                    if ctx is not None:
                        ctx.raw_exception_type = type(err).__name__
                        ctx.raw_exception_text = str(err)
                    raise

                if ctx is not None and raw_result is not None:
                    ctx.raw_response_type = type(raw_result).__name__

                    is_error_method = getattr(raw_result, "isError", None)
                    if callable(is_error_method):
                        try:
                            ctx.raw_is_error = bool(is_error_method())
                        except Exception:
                            ctx.raw_is_error = None

                    ctx.raw_exception_code = self._safe_int(
                        getattr(raw_result, "exception_code", None)
                    )
                    ctx.raw_function_code = self._safe_int(
                        getattr(raw_result, "function_code", None)
                    )
                    ctx.raw_retries = self._safe_int(
                        getattr(raw_result, "retries", None)
                    )
                    ctx.raw_transaction_id = self._safe_int(
                        getattr(raw_result, "transaction_id", None)
                    )

                return raw_result

            self._wrapped_pb_funcs[call_type] = wrapped_pb_func
            pb_request[call_type] = entry._replace(func=wrapped_pb_func)

        # ----------------------------------------------------------
        # HA Modbus error tap.
        # ----------------------------------------------------------
        # Home Assistant deliberately reduces detailed pymodbus errors to a
        # short _log_error() string. Preserve that exact string in JSONL too.
        hub_dict = getattr(self.hub, "__dict__", {})
        self._had_log_error_instance_attr = "_log_error" in hub_dict
        self._previous_log_error_instance_attr = hub_dict.get("_log_error")
        self._original_log_error = self.hub._log_error

        def wrapped_log_error(text: str) -> Any:
            self._schedule_diag(
                "warning",
                "modbus_ha_error",
                error=text,
            )
            return self._original_log_error(text)

        self._wrapped_log_error = wrapped_log_error
        self.hub._log_error = wrapped_log_error

        async def wrapped_low_level_pb_call(
            slave: int | None,
            address: int,
            value: int | list[int],
            use_call: str,
        ) -> Any:
            ctx = self._context.get()
            if ctx is not None and ctx.low_started is None:
                ctx.low_started = monotonic()

            try:
                result = await self._original_low_level_pb_call(
                    slave,
                    address,
                    value,
                    use_call,
                )

                if ctx is not None and result is not None:
                    ctx.low_response_type = type(result).__name__

                    is_error_method = getattr(result, "isError", None)
                    if callable(is_error_method):
                        try:
                            ctx.low_is_error = bool(is_error_method())
                        except Exception:  # Diagnostic only.
                            ctx.low_is_error = None

                    code = getattr(result, "exception_code", None)
                    if code is not None:
                        try:
                            ctx.exception_code = int(code)
                        except (TypeError, ValueError):
                            ctx.exception_code = None

                return result
            finally:
                if ctx is not None:
                    ctx.low_finished = monotonic()

        async def wrapped_async_pb_call(
            unit: int | None,
            address: int,
            value: int | list[int],
            use_call: str,
        ) -> Any:
            started = monotonic()
            ctx = _CallContext(started=started)
            token = self._context.set(ctx)

            self._active_calls += 1
            self._window_max_in_flight = max(
                self._window_max_in_flight,
                self._active_calls,
            )
            self._summary_max_in_flight = max(
                self._summary_max_in_flight,
                self._active_calls,
            )

            result: Any = None
            raised = False
            try:
                result = await self._original_async_pb_call(
                    unit,
                    address,
                    value,
                    use_call,
                )
                return result
            except Exception:
                raised = True
                raise
            finally:
                finished = monotonic()

                queue_wait_ms: float | None = None
                transaction_ms: float | None = None
                post_transaction_ms: float | None = None
                lock_hold_ms: float | None = None

                if ctx.low_started is not None:
                    queue_wait_ms = max(
                        0.0,
                        (ctx.low_started - started) * 1000.0,
                    )

                    if ctx.low_finished is not None:
                        transaction_ms = max(
                            0.0,
                            (ctx.low_finished - ctx.low_started) * 1000.0,
                        )
                        post_transaction_ms = max(
                            0.0,
                            (finished - ctx.low_finished) * 1000.0,
                        )

                    # From low-level start until async_pb_call returns the HA hub
                    # still owns its serialization lock.
                    lock_hold_ms = max(
                        0.0,
                        (finished - ctx.low_started) * 1000.0,
                    )

                self._samples.append(
                    _Sample(
                        finished=finished,
                        address=int(address),
                        call_type=str(use_call),
                        category=_classify(int(address), str(use_call)),
                        success=(not raised and result is not None),
                        total_ms=max(0.0, (finished - started) * 1000.0),
                        queue_wait_ms=queue_wait_ms,
                        transaction_ms=transaction_ms,
                        post_transaction_ms=post_transaction_ms,
                        lock_hold_ms=lock_hold_ms,
                        response_type=ctx.low_response_type,
                        exception_code=ctx.exception_code,
                        request_value=value,
                        raw_response_type=ctx.raw_response_type,
                        raw_is_error=ctx.raw_is_error,
                        raw_exception_code=ctx.raw_exception_code,
                        raw_function_code=ctx.raw_function_code,
                        raw_retries=ctx.raw_retries,
                        raw_transaction_id=ctx.raw_transaction_id,
                        raw_exception_type=ctx.raw_exception_type,
                        raw_exception_text=ctx.raw_exception_text,
                    )
                )

                sample = self._samples[-1]

                # Separate immediate records survive even if the next periodic
                # 30-second report is never reached.
                if not sample.success:
                    self._schedule_diag(
                        "warning",
                        "modbus_call_failed",
                        **self._sample_details(sample),
                    )
                elif (
                    sample.transaction_ms is not None
                    and sample.transaction_ms >= SLOW_TRANSACTION_MS
                ):
                    self._schedule_diag(
                        "warning",
                        "modbus_slow_call",
                        threshold_ms=SLOW_TRANSACTION_MS,
                        **self._sample_details(sample),
                    )

                self._active_calls = max(0, self._active_calls - 1)
                self._context.reset(token)

        self._wrapped_async_pb_call = wrapped_async_pb_call
        self._wrapped_low_level_pb_call = wrapped_low_level_pb_call

        # Instance-level replacement keeps the original HA class untouched.
        self.hub.low_level_pb_call = self._wrapped_low_level_pb_call
        self.hub.async_pb_call = self._wrapped_async_pb_call

        self._installed = True
        self._started_at = monotonic()
        self._last_report_at = self._started_at
        self._last_summary_at = self._started_at

        await self._diag(
            "info",
            "modbus_load_monitor_started",
            report_interval_seconds=self.report_interval,
            summary_interval_seconds=self.summary_interval,
            configured_message_wait_ms=self.configured_message_wait_ms,
        )

        self._task = asyncio.create_task(
            self._report_loop(),
            name="bolid-modbus-load-monitor",
        )

    async def stop(self) -> None:
        """Stop reporting and restore original hub methods."""
        self._stopping = True

        if self._task is not None:
            self._task.cancel()
            try:
                await self._task
            except asyncio.CancelledError:
                pass
            self._task = None

        if not self._installed:
            return

        hub_dict = getattr(self.hub, "__dict__", {})

        # Restore only if our wrappers are still installed. If something else
        # replaced them after us, do not overwrite that newer owner.
        if hub_dict.get("async_pb_call") is self._wrapped_async_pb_call:
            if self._had_async_instance_attr:
                self.hub.async_pb_call = self._previous_async_instance_attr
            else:
                delattr(self.hub, "async_pb_call")

        if hub_dict.get("low_level_pb_call") is self._wrapped_low_level_pb_call:
            if self._had_low_instance_attr:
                self.hub.low_level_pb_call = self._previous_low_instance_attr
            else:
                delattr(self.hub, "low_level_pb_call")

        if hub_dict.get("_log_error") is self._wrapped_log_error:
            if self._had_log_error_instance_attr:
                self.hub._log_error = self._previous_log_error_instance_attr
            else:
                delattr(self.hub, "_log_error")

        pb_request = getattr(self.hub, "_pb_request", {})
        for call_type, original_entry in self._original_pb_entries.items():
            current_entry = pb_request.get(call_type)
            wrapped_func = self._wrapped_pb_funcs.get(call_type)
            if (
                current_entry is not None
                and wrapped_func is not None
                and current_entry.func is wrapped_func
            ):
                pb_request[call_type] = original_entry

        self._installed = False

    async def _report_loop(self) -> None:
        """Write short windows and a longer rolling summary."""
        while not self._stopping:
            await asyncio.sleep(self.report_interval)
            now = monotonic()

            await self._emit_report(
                message="modbus_load",
                start=self._last_report_at,
                end=now,
                max_in_flight=self._window_max_in_flight,
            )
            self._last_report_at = now
            self._window_max_in_flight = self._active_calls

            if now - self._last_summary_at >= self.summary_interval:
                summary_start = max(
                    self._started_at,
                    now - self.summary_interval,
                )
                await self._emit_report(
                    message="modbus_load_summary",
                    start=summary_start,
                    end=now,
                    max_in_flight=self._summary_max_in_flight,
                )
                self._last_summary_at = now
                self._summary_max_in_flight = self._active_calls

            # Keep only the longest interval plus one short-window margin.
            keep_after = now - max(
                self.summary_interval,
                self.report_interval,
            ) - self.report_interval
            while self._samples and self._samples[0].finished < keep_after:
                self._samples.popleft()

    async def _emit_report(
        self,
        message: str,
        start: float,
        end: float,
        max_in_flight: int,
    ) -> None:
        """Aggregate calls completed in [start, end)."""
        samples = [
            sample
            for sample in self._samples
            if start <= sample.finished < end
        ]

        duration = max(0.001, end - start)
        request_count = len(samples)
        success_count = sum(1 for sample in samples if sample.success)
        failed_count = request_count - success_count

        total_values = [sample.total_ms for sample in samples]
        queue_values = [
            sample.queue_wait_ms
            for sample in samples
            if sample.queue_wait_ms is not None
        ]
        transaction_values = [
            sample.transaction_ms
            for sample in samples
            if sample.transaction_ms is not None
        ]
        post_values = [
            sample.post_transaction_ms
            for sample in samples
            if sample.post_transaction_ms is not None
        ]
        lock_hold_values = [
            sample.lock_hold_ms
            for sample in samples
            if sample.lock_hold_ms is not None
        ]

        category_counts = Counter(sample.category for sample in samples)
        call_type_counts = Counter(sample.call_type for sample in samples)
        address_counts = Counter(
            f"{sample.call_type}:{sample.address}"
            for sample in samples
        )

        failed_samples = [sample for sample in samples if not sample.success]
        failed_by_category = Counter(sample.category for sample in failed_samples)
        failed_by_call_type = Counter(sample.call_type for sample in failed_samples)
        failed_addresses = Counter(
            f"{sample.call_type}:{sample.address}"
            for sample in failed_samples
        )
        failed_exception_codes = Counter(
            str(sample.exception_code) if sample.exception_code is not None else "unknown"
            for sample in failed_samples
        )
        failed_response_types = Counter(
            sample.response_type or "none"
            for sample in failed_samples
        )
        failures = [
            {
                "category": sample.category,
                "call_type": sample.call_type,
                "address": sample.address,
                "exception_code": sample.exception_code,
                "response_type": sample.response_type,
                "raw_response_type": sample.raw_response_type,
                "raw_is_error": sample.raw_is_error,
                "raw_exception_code": sample.raw_exception_code,
                "raw_function_code": sample.raw_function_code,
                "raw_retries": sample.raw_retries,
                "raw_transaction_id": sample.raw_transaction_id,
                "raw_exception_type": sample.raw_exception_type,
                "raw_exception_text": sample.raw_exception_text,
                "request_value": sample.request_value,
                "total_ms": round(sample.total_ms, 2),
                "queue_wait_ms": round(sample.queue_wait_ms, 2) if sample.queue_wait_ms is not None else None,
                "transaction_ms": round(sample.transaction_ms, 2) if sample.transaction_ms is not None else None,
            }
            for sample in failed_samples[:20]
        ]

        slow_samples = [
            sample
            for sample in samples
            if (
                sample.transaction_ms is not None
                and sample.transaction_ms >= SLOW_TRANSACTION_MS
            )
        ]
        slow_calls = [
            self._sample_details(sample)
            for sample in slow_samples[:20]
        ]

        # async_pb_call() holds one serialization lock from low_level_pb_call()
        # entry until return. Summed lock-hold time therefore approximates the
        # actual HA Modbus hub occupancy during this wall-clock window.
        lock_hold_total_ms = sum(lock_hold_values)
        hub_lock_utilization_pct = min(
            100.0,
            lock_hold_total_ms / (duration * 1000.0) * 100.0,
        )

        await self._diag(
            "info",
            message,
            window_seconds=round(duration, 3),
            requests=request_count,
            requests_per_second=round(request_count / duration, 3),
            successful=success_count,
            failed=failed_count,
            active_calls_at_report=self._active_calls,
            max_in_flight=max_in_flight,
            configured_message_wait_ms=self.configured_message_wait_ms,
            hub_lock_utilization_pct=round(hub_lock_utilization_pct, 2),
            latency_ms={
                "total_call": _stats(total_values),
                "queue_wait": _stats(queue_values),
                "transaction": _stats(transaction_values),
                "post_transaction": _stats(post_values),
                "lock_hold": _stats(lock_hold_values),
            },
            categories=dict(sorted(category_counts.items())),
            call_types=dict(sorted(call_type_counts.items())),
            top_addresses=dict(address_counts.most_common(12)),
            failed_by_category=dict(sorted(failed_by_category.items())),
            failed_by_call_type=dict(sorted(failed_by_call_type.items())),
            failed_addresses=dict(failed_addresses.most_common(20)),
            failed_exception_codes=dict(sorted(failed_exception_codes.items())),
            failed_response_types=dict(sorted(failed_response_types.items())),
            failures=failures,
            slow_transaction_threshold_ms=SLOW_TRANSACTION_MS,
            slow_calls=slow_calls,
        )
